sudo: no
dist: trusty
language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pyyaml
# command to run tests
script:
  - export PYTHONPATH=${PWD}
  - coverage run -a tests/test_compatibility.py
  - coverage report
after_success:
  - coveralls
